### ISSUE TITLE
How to install and try?

### ISSUE THREAD

**Issue by alejokalderon** [crayner/Gibbon-Responsive#1]
Hi,

I'm new on Gibbon using and I want to test something that allow the mobile using, can you help me with the step by step to try your development in my Gibbon server?

Thank you in advance.

Regards!

**Comment by crayner** [comment]
@alejokalderon  Sorry I missed this.  Just pushed out a pre-release for v17 of Gibbon.  Details, including how to install at http://gibhelp.craigrayner.com

**Comment by crayner** [comment]
Version 0.0.09 and the help site updated to help with initial installation.
